name:                gpvm
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/gpvm#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - transformers >= 0.5
  - vector >= 0.0
  - random
  - mtl
  - criterion

ghc-options:
  - -Wall

library:
  source-dirs: src

default-extensions:
  - PatternSynonyms
  - ViewPatterns
  - TypeApplications
  - DataKinds
  - ConstraintKinds
  - MultiParamTypeClasses
  - TypeFamilies
  - ScopedTypeVariables
  - FlexibleInstances
  - OverloadedLabels
  - RankNTypes
  - NamedFieldPuns
  - RecordWildCards
  - DuplicateRecordFields
  - OverloadedLists
  - DisambiguateRecordFields
  - BangPatterns

executables:
  gpvm-exe:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - gpvm
    ghc-options: -rtsopts

benchmarks:
  gpvm-bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - gpvm
